services:
  # PostgreSQL Database
  - type: pserv
    name: workout-tracker-db
    plan: free
    region: oregon
    databaseName: workout_tracker
    user: postgres

  # Node.js Backend
  - type: web
    name: workout-tracker-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: cd server && npm install && npx prisma generate
    startCommand: cd server && npx prisma migrate deploy && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: workout-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: CORS_ORIGIN
        value: https://workout-tracker-frontend.onrender.com

  # React Frontend
  - type: web
    name: workout-tracker-frontend
    runtime: static
    plan: free
    region: oregon
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://workout-tracker-backend.onrender.com/api

  # Optional: Redis for caching (free tier)
  - type: redis
    name: workout-tracker-cache
    plan: free
    region: oregon
